# Generated by Django 3.0.4 on 2020-05-02 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200402_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('todoslospermisos', 'todoslospermisos'),)},
        ),
    ]
