# Generated by Django 3.0.4 on 2020-04-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carguecv', '0018_auto_20200419_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carga_cv',
            name='estado',
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carguecv.Cargo'),
        ),
    ]
