# Generated by Django 3.0.4 on 2020-04-29 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carguecv', '0019_auto_20200429_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga_cv',
            name='archivo_cv',
            field=models.FileField(null=True, upload_to='Cv/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carguecv.Cargo'),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='foto',
            field=models.FileField(null=True, upload_to='Foto/%Y/%m/%d'),
        ),
    ]
