# Generated by Django 3.0.4 on 2020-04-30 02:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carguecv', '0023_auto_20200429_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Areas',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='Centro_educativo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='Empresa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='Estado_estudio',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='Funciones',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='Nivel_educativo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='Periodo_fin',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 21, 21, 40, 773728)),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='Periodo_inicio',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 21, 21, 40, 773728)),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carguecv.Cargo'),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='cedula',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='estado_civil',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='genero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='nivel',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='departamento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='municipio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tipo_identificacion',
            name='Tipo_identificacion',
            field=models.CharField(max_length=20),
        ),
    ]
